### ISSUE TITLE
Citing Vesper

### ISSUE THREAD

**Issue by lostanlen** [HaroldMills/Vesper#129]
Hello @HaroldMills,
I am writing a paper which evaluates the Old Bird flight call detectors in Vesper. It would be good if Vesper were registered on zenodo so that I could have a DOI to point to.
Or maybe you prefer that I cite an academic paper of yours?

**Comment by HaroldMills** [comment]
Hi @lostanlen,
I have registered Vesper with Zenodo: thanks for the suggestion. I also added a DOI badge for all versions of Vesper to the [README](https://github.com/HaroldMills/Vesper/blob/master/README.md) and one specifically for v0.3.12 to its [release notes](https://github.com/HaroldMills/Vesper/releases/tag/v0.3.12). v0.3.12 was just released this morning, but it contains version 1.1 of the Old Bird Redux detectors, which I believe are what you evaluated.

**Comment by HaroldMills** [comment]
Registered Vesper with Zenodo and added DOI badges to Vesper README and release notes on October 18.
