### ISSUE TITLE
Improve clip calendar and clip album handling of missing archive objects.

### ISSUE THREAD

**Issue by HaroldMills** [HaroldMills/Vesper#152]
Vesper currently does not handle missing archive objects very well in clip calendar and clip album views. As of fda628b83b7b0d2e8c2e42b08204e4da112214bc, both views handle empty archives better than they use to (they deliver a 404 response rather than raising an exception), but not as well as they should. Both views should display a clear error message (on a page delivered with HTTP status 200) when the archive is empty, as well as when it is not but a requested station/mic, detector, or annotation does not exist.

This issue succeeds #150.

**Comment by RichardLitt** [comment]
Hey @HaroldMills. This is still a real blocker for me, when it comes to setting up different archives. I can't remember how to fix this issue; I've tried manually importing Preferences.yaml, Classifier.yaml, Redux\ Detectors.yaml, and migrating databases, creating a new superuser after each migration, and importing audio. But I can't get see the clip calendar.

In lieu of fixing the bug, could you write the steps here for fixing the station_mic missing issue?

**Comment by RichardLitt** [comment]
I got it evenutally. It looks like manually adding the right .yaml file - in my case, the one `Archive Data/Vesper NBNC Archive Data.yaml`, into the Import Archive Data solved this problem. Should we add this to the Wiki?

**Comment by HaroldMills** [comment]
Hi @RichardLitt - I've added an [FAQ](https://github.com/HaroldMills/Vesper/wiki/FAQ) to the wiki, including a question that I hope will help with this issue. I'm working on getting Vesper 0.4.8 ready, including the create-an-archive tutorial mentioned in the FAQ, which I intend will take care of this issue.

**Comment by RichardLitt** [comment]
Thanks, @HaroldMills.

**Comment by HaroldMills** [comment]
This issue was resolved by Vesper 0.4.8.

**Comment by RichardLitt** [comment]
Thank you, @HaroldMills!
