### ISSUE TITLE
No detection intervals

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#159]
I've run across this error when trying to detect on a clip:

```
[08/Mar/2020 09:43:33] "POST /detect/ HTTP/1.1" 302 0
2020-03-08 09:43:33,801 INFO     Job started for command "detect" with arguments:
2020-03-08 09:43:33,802 INFO         {
2020-03-08 09:43:33,803 INFO             "detectors": [
2020-03-08 09:43:33,803 INFO                 "Old Bird Thrush Detector Redux 1.1"
2020-03-08 09:43:33,803 INFO             ],
2020-03-08 09:43:33,803 INFO             "stations": [
2020-03-08 09:43:33,803 INFO                 "MSGR"
2020-03-08 09:43:33,803 INFO             ],
2020-03-08 09:43:33,803 INFO             "start_date": "2020-01-01",
2020-03-08 09:43:33,803 INFO             "end_date": "2021-01-01",
2020-03-08 09:43:33,803 INFO             "schedule": "Ithaca 2019",
[08/Mar/2020 09:43:33] "GET /jobs/9/ HTTP/1.1" 200 6522
2020-03-08 09:43:33,803 INFO             "defer_clip_creation": false
2020-03-08 09:43:33,803 INFO         }
2020-03-08 09:43:33,819 INFO     This command will process recordings for 1 station-night.
2020-03-08 09:43:33,819 INFO     Processing recordings for station-night 1 of 1 - "MSGR 2020-03-04"...
2020-03-08 09:43:33,823 INFO         Processing recording 1 of 1 - "MSGR / PC / start 2020-03-04 21:36:23+00:00 / duration 6.874 h"...
2020-03-08 09:43:34,220 INFO             There are no detection intervals in file "/Users/richard/src/msgr-vesper-archive/Recordings/MSGR_2020-03-04_21.36.23_Z.wav", so no detectors will be run on it.
2020-03-08 09:43:34,223 INFO     Job complete.
```

Any ideas? Is it possible that my clip simply has no birds in it?

**Comment by HaroldMills** [comment]
Hi Richard,

From the log you sent, it looks like your recording is from 2020, while
your detection schedule ("Ithaca 2019") might be just for 2019. I would
suggest running the detector with no detection schedule.

I'd be interested to hear what calls you get in early March.

Cheers,

    Harold

P.S. Vesper 0.4.8 is still on its way. If you're interested, you can see a
draft of the user documentation here
<https://vesper.readthedocs.io/en/latest/>. Vesper 0.4.8 will include
support for the latest version of BirdVoxDetect, which has considerably
higher recall and precision than the Old Bird detectors on almost all
recordings.

**Comment by RichardLitt** [comment]
Looks like it was just by using the detection schedule that this was a problem. Running without it solved it. 

Nothing yet, that I can tell! I heard some possible migrating tseeps on top of a mountain here last night, as well as migrating Canada Geese.

**Comment by RichardLitt** [comment]
Interestingly, I ran into another problem when trying to show you what was detected. These two tseeps were found:

<img width="1413" alt="Screen Shot 2020-03-09 at 09 55 24" src="https://user-images.githubusercontent.com/910753/76219414-2fc77b80-61ec-11ea-8785-4212a94e2f93.png">

Unfortunately, I can't export them. When I export clips, it exports all of the clips. However, none of the clips names match the time stamp shown beneath these pictures. Also, the first call at 17:44:28 doesn't make sense, as on March 8th I started recording at 20:30. Any ideas what I am missing here?

**Comment by RichardLitt** [comment]
Looking forward to when `pip install vesper==0.4.8` works. :)

**Comment by HaroldMills** [comment]
I would check the names of the recording files you're importing. Do they specify the correct recording start times? The start time listed in your opening comment is 2020-03-04 21:36:23+00:00. That's a UTC time, which in the US/Eastern time zone is 2020-03-04 16:36:23 EST, i.e. 4:36 pm.

**Comment by RichardLitt** [comment]
Is that what the _Z is specifying, Zulu time? Is there a way to specify the Eastern time zone in the name of my audio files, and still have them be imported?

**Comment by HaroldMills** [comment]
Yes, the _Z means "Zulu" or UTC, in both the recording file names and the exported clip file names. Vesper can import recording files with names that specify local times in the form <station name>_yyyymmdd_hhmmss.wav, e.g. MSGR_20200304_213623.wav. But note that there's a tradeoff here: in favor of local times, if you use UTC times in file names but want to think in terms of local time (which we often do), you have to remember to convert when you look at the UTC times, which can be confusing. But the UTC times are more standard, explicit, and unambiguous, which is a big advantage, especially if you deal with data from multiple time zones, or if you or somebody else might work with your recordings years down the line. If you want your data to have greater long-term value, I think it's best to use UTC. Vesper uses only UTC internally, and favors it for import and export, but converts to and from local time in the user interface.

Regarding clip exports, In Vesper 0.4.8 can export clips selected by detector(s), station(s), classification, and range of nights.

**Comment by RichardLitt** [comment]
Is there a way to change the view of the clip calendar to show the timezone I uploaded it in? I'm fine using UTC in the file names, but it would be great if I could see, in the view above, both times.

**Comment by RichardLitt** [comment]
(On an unrelated note; I think that's a Tufted Titmouse. Which isn't exactly a migrant, but is interesting, I suppose!)

**Comment by HaroldMills** [comment]
@RichardLitt, could you please clarify what you'd like to see? Is your request for the clip calendar (i.e. the page that shows a calendar with orange bubbles of various sizes indicating clip counts by date) and/or the clip album (i.e. a page that shows clip spectrograms, which can be displayed either by clicking on a clip calendar bubble or by selecting "View->View clip album", with an album displayed from a clip calendar including a rug plot towards the top, showing the start times of clips for the night of the album)? Currently, both the clip calendar and the clip album can display dates and times only in the station's local time zone.

**Comment by RichardLitt** [comment]
The clip album should show clips in the local time of the station, even if the sound files are imported as UTC. While it makes sense to have the data in UTC (as you describe above), it's confusing that the clip album times are displayed as UTC, as, as a user, I want to know when a bird passed over relative to the time zone I am actually in (if I am in the same place as a station). 

Basically: from a data perspective, going with UTC makes sense. But from a UI perspective, as someone going through the recordings, I want to know automatically without doing mental calculation that a bird was recorded at 4am. 

Does this help?

**Comment by HaroldMills** [comment]
Thanks for the clarification. The clip album is already supposed to do exactly what you're suggesting, since as you said it makes more sense to display local times instead of UTC times in the user interface. If you're seeing UTC times in the UI, could you please zip up your archive, minus the recording files, and send it to me so I can try to figure out what's going wrong?

**Comment by RichardLitt** [comment]
Done - here's the [repo](https://github.com/RichardLitt/msgr-vesper-archive).

**Comment by HaroldMills** [comment]
Thanks for the archive. The archive database shows two recordings, one starting at 2020-03-04 21:36:23 UTC and the other starting at 2020-03-08 20:30:00 UTC. These start times are presumably incorrect, but were specified in the names your recording files had when they were imported. The archive also includes 3605 clips for these recordings, all of which have similarly incorrect start times.

The most straightforward remedy would probably be to delete the recordings from your archive (this will delete the recordings and all of their clips from the archive database, but it won't delete the recording files), make sure the recording file names specify the correct start times (2020-03-05 02:36:23 UTC and 2020-03-09 00:30:00 UTC) , and reimport and reprocess your recordings.

It's a bummer to have to reprocess the recordings, but Vesper does not currently support correcting the start times of recordings (and their clips) once they have been imported. I see that there are only 22 clips in the archive with classifications other than "Noise": you may know this already, but your "Coarse" clip album commands preset allows you to classify all of the clips of a recording as "Noise" with the command "*N". So you can correctly classify all but 22 of your clips with one command for each recording, and then find and reclassify those 22.

What recording software are you using? Can it name your recording files with UTC start times?

**Comment by RichardLitt** [comment]
You're, of course, right. Thanks for bearing with me. I've renamed the files and reran everything, which takes five minutes and is trivial on my machine given the data size.

I can confirm that it now works as expected. Note the American Tree Sparrows this morning (cool!):

<img width="1793" alt="Screen Shot 2020-03-10 at 11 55 13" src="https://user-images.githubusercontent.com/910753/76332282-8c976480-62c6-11ea-983f-4fed31b26cc9.png">

Can I export only non-noise clips?

I'm using I-Sound recorder, and manually rename the files when I import then to my mac.

**Comment by HaroldMills** [comment]
Glad to hear it's working! You can export clips by classification (e.g. Call*) in Vesper 0.4.8, which I hope to release this week.
