### ISSUE TITLE
vesper_admin not found

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#163]
I recently switched to zsh, thanks to OSX changing their default, and this may have messed some things up for me. I had to reinstall conda. After doing so, I found that vesper_admin isn't found anymore. Any ideas on how I can diagnose this? 

```sh
msgr-vesper-archive git:(master) ✗ conda activate vesper-0.4.8
(vesper-0.4.8) ➜  msgr-vesper-archive git:(master) ✗ vesper_admin runserver
zsh: command not found: vesper_admin
```

**Comment by HaroldMills** [comment]
I use macOS Catalina and zsh, and vaguely remember a Catalina/zsh bump, but unfortunately not details. The (I think) relevant portion of my .zprofile looks like this::

    # >>> conda initialize >>>
    # !! Contents within this block are managed by 'conda init' !!
    __conda_setup="$('/Users/harold/miniconda3/bin/conda' 'shell.bash' 'hook' 2> /dev/null)"
    if [ $? -eq 0 ]; then
        eval "$__conda_setup"
    else
        if [ -f "/Users/harold/miniconda3/etc/profile.d/conda.sh" ]; then
            . "/Users/harold/miniconda3/etc/profile.d/conda.sh"
        else
            export PATH="/Users/harold/miniconda3/bin:$PATH"
        fi
    fi
    unset __conda_setup
    # <<< conda initialize <<<

The second line suggests that `conda init` might be helpful to you. You can read about it with `conda init --help`. Maybe the answer is just `conda init zsh`?

**Comment by RichardLitt** [comment]
Hmm. Throwing that in my .zshrc, and trying `conda init zsh`, didn't produce any results for vesper_admin. Any other ideas?

**Comment by RichardLitt** [comment]
I had to reinstall using `pip install vesper==0.4.8`, and then restart conda. Got it!
