### ISSUE TITLE
Unable to edit calls presets

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#165]
Editing a line by adding another bird in `Presets/Clip Album Commands/Calls.yaml` and a corresponding line in `Archive Data/Vesper MSGR Archive Data.yaml` does not add the call to the presets. It also removes the "Calls" option in the "Command Presets" dropdown in the "Edit Settings" modal, opened from the Calendar View in the web interface.

How can I edit the Calls presets?

**Comment by HaroldMills** [comment]
If your "Calls" preset disappeared from the "Command Presets" dropdown, it's likely that there's a syntax error in the preset.
I've added a [FAQ](https://vesper.readthedocs.io/en/latest/faq.html) section to the Vesper documentation with a couple of items that describe how to add species to the Vesper UI and clip album command presets. Please read them, try your addition again, and let me know if there are still problems. Good luck!

**Comment by RichardLitt** [comment]
Thanks for the added FAQ! I found the error; I failed to notice that the shortcut key I used as used twice. Might be good to log an error for this instead of simply disabling the Calls section, but for now, this can be resolved. Thanks Harold.
