### ISSUE TITLE
Allow specification of desired duration of exported clip audio files.

### ISSUE THREAD

**Issue by HaroldMills** [HaroldMills/Vesper#167]
The existing `Export clips to audio files` command does not allow any control of the duration of the exported files. It would be helpful (see, for example, #166) to allow specification of the desired duration of the files. The specification should be optional, and if it is not provided the clips should be exported as they are now. If the specification is provided, issues to consider are how to justify the clips in the output (e.g. left, center, or right, possibly with padding of a fixed duration), and whether or not to substitute zeros for unobtainable samples.

**Comment by RichardLitt** [comment]
I like this idea.

**Comment by HaroldMills** [comment]
This is fixed in 62c038f28b0b2b0245db1dcf9172142b8191a898, and available in the 0.4.11 alpha releases. Exported clip durations and padding can now be specified in Clip Audio File Export Settings presets, selectable from the export form. Documented examples of the new preset type are included in the archive template.

**Comment by RichardLitt** [comment]
That's great! This means we can change it to a few seconds, allowing us to upload it to eBird easier. Awesome! Thanks Harold.

**Comment by RichardLitt** [comment]
This works great. Thank you, Harold!
