### ISSUE TITLE
Add option to limit Clip Album by date

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#170]
My current process is to import recordings, detect, and classify them. Then, I go through the previous night and look for any calls I can definitely identify as a given bird. When I have those, I use the calls elector to identify them as a given bird. Then, I use the Clip Album to show all identified birds, so that I can mark them in an eBird checklist. If a call is particularly good, I'll export it and add it to the checklist. 

I'd like to be able to filter the Clip Albums by date to make this process a bit easier.

**Comment by RichardLitt** [comment]
Thanks, @HaroldMills. I'm not sure what I meant, either. Let me close this for, for now, and if I remember what I was looking for, I'll reopen it in the future with a better description. Thanks for the feedback on lack of clarity!

**Comment by HaroldMills** [comment]
Thanks for tending to this!
