### ISSUE TITLE
Logs, status, and times do not change for detect and classify in web view

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#173]
When running the Detect or Classify Jobs, the Status, Times, and Log do not change in the web view. 

<img width="806" alt="Screen Shot 2020-09-06 at 04 53 24" src="https://user-images.githubusercontent.com/910753/92322064-0e114a80-effd-11ea-8354-5bf6cf1e5978.png">

Some output is provided at the beginning. However, this is never updated. Here's a shot of the finished logs in the terminal, which I watch, instead. 

<img width="846" alt="Screen Shot 2020-09-06 at 04 53 35" src="https://user-images.githubusercontent.com/910753/92322086-28e3bf00-effd-11ea-8ef2-40ce13285b3d.png">

**Comment by HaroldMills** [comment]
Superseded by #175.
