### ISSUE TITLE
Not sure how to reimport annotation_constraints

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#177]
The values.Call fields under annotation_constraints aren't editable. I can save the file, but it doesn't change it when restarting vesper. However, I can't reimport the entire file due to uniqueness issues. Should I try just importing my new `annotation_constraints` if I want to change a species there?

**Comment by HaroldMills** [comment]
You can't reimport an annotation constraint, since that would violate a database uniqueness constraint. You can, however, edit an existing annotation constraint using Django's admin interface, as described in section 3.1 of the [Vesper FAQ](https://vesper.readthedocs.io/en/latest/faq.html).

**Comment by RichardLitt** [comment]
Thank you! This worked.
