### ISSUE TITLE
Vesper module has no __version__ (PEP 396)

### ISSUE THREAD

**Issue by lostanlen** [HaroldMills/Vesper#180]
Hello!
It took me some time to realize that the version number for Vesper is located in `vesper.version.full_version`

In the spirit of PEP 396 (https://www.python.org/dev/peps/pep-0396/), i think it would be good to define the `vesper.__version__` constant as an alias to `vesper.version.full_version`

**Comment by HaroldMills** [comment]
Thanks for reporting this, Vincent. I will fix for the upcoming 0.4.9 release.

**Comment by HaroldMills** [comment]
Fixed in 8ab3aca589cc731e9cce71ce55bc9372c8ef5479.
