### ISSUE TITLE
BirdVox suggests birds from the wrong side of the ocean

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#193]
I'm running Vesper currently in the UK. It keeps suggesting GCTH and SAVS. Do you know if this is an issue with BirdVox, or with Vesper's implementation and BirdVox not reading the station's coordinates?

**Comment by HaroldMills** [comment]
BirdVoxDetect (and every other existing NFC detector, to my knowledge) does the same thing for every recording it runs on, regardless of where the recording was made. Vesper currently makes no attempt to compensate for this. That will change as the available software matures, but for now that's where things stand.

**Comment by RichardLitt** [comment]
Good to know. Maybe I've found the first GCTHs in Britain this year. Unlikely, but hey. 

Thanks. Might be good to add to the FAQ doc.
