### ISSUE TITLE
Recordings cannot have capitalized file-endings

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#206]
You cannot import `Test_20221010_020202.WAV`, but the same works if it is changed to `.wav`. I'm not sure this is a necessary check.

**Comment by HaroldMills** [comment]
Thanks for reporting this issue. It is now fixed, and the fix will appear in the next Vesper release.

**Comment by RichardLitt** [comment]
Thanks for fixing it!
