### ISSUE TITLE
Shortcut for switching classifiers

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#214]
I know that we can use a single classifier instead of using Coarse and Eastern, but I wonder if there is a way to change classifiers using a shortcut that could be listed in the classifier itself. 

For instance: 

```
    "=": [toggle_classifiers]
```

**Comment by RichardLitt** [comment]
Thanks Harold. This isn't documented anywhere that I know of - should we add it to the ReadTheDocs, or to the default presets, perhaps?

**Comment by HaroldMills** [comment]
I've added:

    "%c": [set_clip_album_commands_preset, Coarse]
    "%e": [set_clip_album_commands_preset, Eastern Calls]
    "%w": [set_clip_album_commands_preset, Western Calls]

    "%b": [set_clip_album_settings_preset, With Background Normalization]
    "%x": [set_clip_album_settings_preset, Without Background Normalization]

to all of the the Clip Album Commands presets of the archive template. Note that I've included commands for changing both the Clip Album Commands preset and the Clip Album Settings preset.

**Comment by RichardLitt** [comment]
Thank you!
