### ISSUE TITLE
Unclear how to cite Vesper

### ISSUE THREAD

**Issue by RichardLitt** [HaroldMills/Vesper#224]
I came across a use case where I am trying to cite Vesper, and the best I have to go on is the Zenodo link. That seems a bit odd to me - is there a paper for it, yet?

**Comment by HaroldMills** [comment]
There isn't a Vesper paper yet. For the time being the Zenodo link is the best option.

**Comment by RichardLitt** [comment]
Have you considered writing up a paper and submitting it to JOSS? https://joss.theoj.org/about
