### ISSUE TITLE
Offer more clip text display options.

### ISSUE THREAD

**Issue by HaroldMills** [HaroldMills/Vesper#72]
The text for a clip is currently displayed on top of the spectrogram in order to conserve space. However, the text is sometimes difficult to read there. Move the text to underneath the spectrogram so it will always be visible. It might be good to allow the text to be displayed within the spectrogram as an option, but the default should probably be underneath.

**Comment by wrevans** [comment]
Hi Harold,
I’d like to follow-up on our call yesterday if you have time for a brief phone call this morning.

Bill

**Comment by HaroldMills** [comment]
Debbie Leick mentioned this issue again last week. The text as currently displayed sometimes obscures portions of spectrograms that she would like to see. She would rather not have the text displayed underneath the spectrograms, since she would like to be able to fit as many spectrograms as possible on a single viewer page. She suggested that showing the text in tooltips might work well for her.

**Comment by HaroldMills** [comment]
This issue was fixed in f6a85912262ebffaf205649aeef680f622f9e044. Labels can now be displayed in various places both inside and outside of clip views, and their visibility can be toggled with a keystroke.
